{% set name = "pyannote.database" %}
{% set version = "5.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyannote.database-{{ version }}.tar.gz
  sha256: 1f8633d1f5091cfd0dd4e2a011749a6194f23996c9b56dbd766be4e9e2db860d

build:
  number: 0
  entry_points:
    - pyannote-database=pyannote.database.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pandas >=0.19
    - pyannote.core >=4.1
    - python
    - pyyaml >=3.12
    - typer >=0.2.1
    - typing-extensions >=3.7.4  # [py<38]

test:
  imports:
    - pyannote
    - pyannote.database
  commands:
    - pip check
    - pyannote-database --help
  requires:
    - pip

about:
  home: http://pyannote.github.io/
  summary: Interface to multimedia databases and experimental protocols
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tyrius02
